---
- hosts: localhost
  tasks:
  - name: install packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - htop
      - vim
      - mysql-workbench

- include: google_chrome.yaml
